# 2025年5月11日(日)

# やったこと📝

- [プラクティス 非同期処理\(JavaScript\) \| FBC](https://bootcamp.fjord.jp/practices/204)
- [JSの非同期処理を理解するために必要だった知識と学習ロードマップ](https://zenn.dev/estra/articles/js-async-programming-roadmap)
- https://jsprimer.net/basic/async/

# わかったこと💡
## promiseと例外
> Promiseではコンストラクタの処理で例外が発生した場合に自動的に例外がキャッチされます。例外が発生したPromiseインスタンスはreject関数を呼び出したのと同じように失敗したものとして扱われます。 そのため、Promise内で例外が発生するとthenメソッドの第二引数やcatchメソッドで登録したエラー時のコールバック関数が呼び出されます。

```javascript
function throwPromise() {
    return new Promise((resolve, reject) => {
        // Promiseコンストラクタの中で例外は自動的にキャッチされrejectを呼ぶ
        throw new Error("例外が発生");
        // 例外が発生すると、これ以降のコンストラクタの処理は実行されません
    });
}

throwPromise().catch(error => {
    console.log(error.message); // => "例外が発生"
});
```
便利ですね！コールバックでは例外処理が難しいみたいですが、promiseは自動でキャッチしてくれるとのことです！

# 次にやること✅

- [プラクティス 非同期処理\(JavaScript\) \| FBC](https://bootcamp.fjord.jp/practices/204)

# いまの気持ち🫶

コールバックでは例外処理が難しいですが、promiseは自動で例外をキャッチしてくれるみたいなので、早く便利さを体感してみたいです！

# 学習時間

- 2時間30分(合計: 267時間30分)
